# GitHub Action for generating a contribution graph with a snake animation

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake contribution graph
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: pratikmishra09
          outputs: dist/github-contribution-grid-snake.svg

      # Commit and push the generated snake animation
      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated Snake Contribution Graph" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
